# Generated by Django 4.2.10 on 2025-09-27 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='student_management_app.students'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('staff_to_admin', 'Staff to Admin'), ('admin_to_staff', 'Admin to Staff'), ('student_to_admin', 'Student to Admin'), ('admin_to_student', 'Admin to Student')], max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='student_management_app.staffs'),
        ),
    ]
