# Generated by Django 4.2.10 on 2025-09-28 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student_management_app', '0004_alter_students_course_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(default='#007bff', help_text='Hex color code', max_length=7)),
            ],
            options={
                'verbose_name': 'File Category',
                'verbose_name_plural': 'File Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title/Name of the file', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description', null=True)),
                ('file', models.FileField(help_text='Upload file', upload_to='files/%Y/%m/%d/')),
                ('file_type', models.CharField(choices=[('document', 'Document'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('archive', 'Archive'), ('other', 'Other')], default='document', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_size', models.BigIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('download_count', models.PositiveIntegerField(default=0, help_text='Number of times downloaded')),
                ('is_public', models.BooleanField(default=True, help_text='Can all students in the subject access this file?')),
                ('is_active', models.BooleanField(default=True, help_text='Is this file active and visible?')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='file_management.filecategory')),
                ('session', models.ForeignKey(help_text='Academic session', on_delete=django.db.models.deletion.CASCADE, to='student_management_app.sessionyearmodel')),
                ('subject', models.ForeignKey(help_text='Subject this file belongs to', on_delete=django.db.models.deletion.CASCADE, to='student_management_app.subjects')),
                ('uploaded_by', models.ForeignKey(help_text='Teacher who uploaded this file', on_delete=django.db.models.deletion.CASCADE, to='student_management_app.staffs')),
            ],
            options={
                'verbose_name': 'Subject File',
                'verbose_name_plural': 'Subject Files',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=False, help_text='Can other students see this note?')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.students')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.sessionyearmodel')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.subjects')),
            ],
            options={
                'verbose_name': 'Student Note',
                'verbose_name_plural': 'Student Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FileAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('view', 'View'), ('download', 'Download'), ('delete', 'Delete')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_management.subjectfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'File Access Log',
                'verbose_name_plural': 'File Access Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='subjectfile',
            index=models.Index(fields=['subject', 'session'], name='file_manage_subject_675223_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectfile',
            index=models.Index(fields=['uploaded_by'], name='file_manage_uploade_c3e355_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectfile',
            index=models.Index(fields=['-uploaded_at'], name='file_manage_uploade_3fc5f0_idx'),
        ),
        migrations.AddIndex(
            model_name='studentnote',
            index=models.Index(fields=['subject', 'session'], name='file_manage_subject_b826b5_idx'),
        ),
        migrations.AddIndex(
            model_name='studentnote',
            index=models.Index(fields=['created_by'], name='file_manage_created_db9c64_idx'),
        ),
        migrations.AddIndex(
            model_name='studentnote',
            index=models.Index(fields=['-created_at'], name='file_manage_created_fa2862_idx'),
        ),
        migrations.AddIndex(
            model_name='fileaccesslog',
            index=models.Index(fields=['file', 'action'], name='file_manage_file_id_7b2540_idx'),
        ),
        migrations.AddIndex(
            model_name='fileaccesslog',
            index=models.Index(fields=['user'], name='file_manage_user_id_103bbe_idx'),
        ),
        migrations.AddIndex(
            model_name='fileaccesslog',
            index=models.Index(fields=['-timestamp'], name='file_manage_timesta_bdc83c_idx'),
        ),
    ]
